### ISSUE TITLE
Doesn't build with recent influx-client

### ISSUE THREAD

**Issue by msiebuhr** [heroku/lumbermill#21]
The client-library moved from `github.com/influxdb/influxdb-go` to `github.com/influxdb/influxdb/client`.

**Comment by apg** [comment]
This actually happened right after we went into production last year. And, lumbermill still targets InfluxDB 0.7.6 for right now, so we don't have much motivation at the moment to fix this.

We will, possibly soon, need to make this all work with newer versions of InfluxDB, which, of course, might break our compatibility with the older versions... :panda_face:

**Comment by gabeweaver** [comment]
We would love to use this, but can't until Lumbermill targets InfluxDB 0.9.6+. Are there any plans for this? The difference between 0.7.6 and 0.9.6.1 is night and day. What are the chances the maintainers will embark on this journey? 

From what i've gathered, there aren't going to be many breaking changes between InfluxDB 0.9.6.1 and 1.0.

**Comment by apg** [comment]
We are still using Lumbermill with InfluxDB 0.7.6, and do not have plans to upgrade to 0.9.6 at this time. 

I don't think it would be a big deal to modify Lumbermill to support 0.9.6, since all the batching and stuff is there, so long as the newer version supports batching, which I assume it does.

**Comment by freeformz** [comment]
We're no longer using lumbermill and it won't be updated by us. Thanks!
